config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :videos, only: [:index, :new, :create] do
    resources :likes
  end

  root to: 'videos#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :video
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :videos, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :username, presence: :true, uniqueness: { case_sensitive: false }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
protected
  def email_required?
   false
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if username = conditions.delete(:username)
      where(conditions.to_h).where(["lower(username) = :value ", { :value => username.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy

  delegate :username, to: :user, prefix: true
  YT_LINK_FORMAT = /\A.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|\&v=)([^#\&\?]*).*/i

  validates :link, presence: true, format: YT_LINK_FORMAT
end

app/models/video_observer.rb
class VideoObserver < ActiveRecord::Observer
    def before_save(resource)
      video = Yt::Video.new url: resource.link
      resource.uid = video.id
      resource.title = video.title
      resource.video_likes = video.like_count
      resource.video_dislikes = video.dislike_count
      resource.description = video.description
      resource.published_at = video.published_at
    rescue Yt::Errors::NoItems
      resource.title = ''
    end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :find_video
  before_action :find_like, only: [:destroy]


  def create
    if already_liked?
      flash[:notice] = "You can't like more than once"
    else
      @video.likes.create(user_id: current_user.id)
    end
    redirect_to videos_path(@video)
  end

  def destroy
    if !(already_liked?)
      flash[:notice] = "Cannot unlike"
    else
      @like.destroy
    end
    redirect_to videos_path(@post)
  end


  private
  def already_liked?
    Like.where(user_id: current_user.id, video_id: params[:video_id]).exists?
  end

  def find_like
    @like = @video.likes.find(params[:id])
  end

  def find_video
    @video = Video.find(params[:video_id])
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
	before_action :authenticate_user!, only: [:new, :create]

	def index
			@videos = Video.order('created_at DESC')
	end
	
	def new
		@video = Video.new
	end

	def create
		@video = Video.new(video_params)
		@video.user_id = current_user.id
		if @video.save
			flash[:success] = 'Video added!'
			redirect_to root_url
		else
			render :new
		end
	end
		
	private
	
	def video_params
		params.require(:video).permit(:link)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShareVideo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <%= link_to 'Funny Videos', root_path, class: 'navbar-brand' %>
        </div>
        <ul class="nav navbar-nav">
         <li><%= link_to 'Videos', root_path %></li>
        <% if user_signed_in? %>
            Logado como: <strong><%= current_user.email %></strong>.
            <li><%= link_to 'Share Videos', new_video_path %></li>
            <li><%= link_to 'Editar perfil', edit_user_registration_path, :class => 'navbar-link' %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'%></li>
          <% else %>
            <li>  <%= link_to "Registrar-se", new_user_registration_path, :class => 'navbar-link'  %></li>
            <li> <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>           
          <% end %>
        </ul>
      </div>
    </div>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>">
          <%= value %>
        </div>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div class="panel panel-danger">
    <div class="panel-heading">
      <h3 class="panel-title">The following errors were found while submitting the form:</h3>
    </div>

    <div class="panel-body">
      <ul>
        <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/videos/index.html.erb
<% if @videos.any? %>
  <div class="container">
    <h1>Latest videos</h1>
    <div id="player-wrapper"></div>
    <% @videos.in_groups_of(1) do |group| %>
      <div class="row">
        <% group.each do |video| %>
          <% if video %>
            <div class="col-md-4">
              <div class="yt_video thumbnail ">
                <%= link_to image_tag("https://img.youtube.com/vi/#{video.uid}/mqdefault.jpg", alt: video.title,
                                      class: 'img-rounded'),
                            "https://www.youtube.com/watch?v=#{video.uid}", target: '_blank' %>
                <div class="caption">
                  <h5><%= video.title %></h5>
                  <p>Published at: <%= video.published_at.strftime('%-d %B %Y %H:%M:%S') %></p>
                  <% if user_signed_in? %>
                    <p>
                      <span class="glyphicon glyphicon glyphicon-thumbs-up"></span> <%= video.video_likes %>
                      <span class="glyphicon glyphicon glyphicon-thumbs-down"></span> <%= video.video_dislikes %>
                    </p>
                  <%end %>
                </div>
              </div>
            </div>
             <div class="col-md-8">
              <h5> Shared By: <%= video.user_username %></h5>
              <h5> Posted At: <%= video.created_at %></h5>
              <br/>
              <% if video.description.present? %>
                <h6> Description:</h6>
                <p> <%= truncate(video.description, :length => 850) %> </p>
                <% else %>
                 <p> This video do not have description! </p>
              <%end%>
              <% if user_signed_in? %>
                <span class="glyphicon glyphicon glyphicon-thumbs-up"></span>
                <p><%= video.likes.count %></p>
                <% pre_like = video.likes.find { |like| like.user_id == current_user.id} %>
                  <% if pre_like %>
                    <%= button_to 'Unlike', video_like_path(video, pre_like), method: :delete %>
                  <% else %>
                    <%= button_to 'Like', video_likes_path(video), method: :post %>
                <% end %>
               <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
  <%else%>
  <div class="jumbotron">
    <div class="container">
      <h1>Share your videos with the world!</h1>
      <p>Click the button below to share your video from YouTube.</p>
      <p>
        <%= link_to 'Add video now!', new_video_path, class: 'btn btn-primary btn-lg' %>
      </p>
    </div>
</div>

<% end %>

app/views/videos/new.html.erb
<div  class=" container">
  <div  class="col-md-offset-3 col-md-6 thumbnail">
    <h1 align="center">Share video</h1>
    <div class="col-md-12">
      <%= form_for @video do |f| %>
        <%= render 'shared/errors', object: @video %>
        <div class="col-md-12">
          <div class="form-group">
            <label>YouTube Url: </label>
            <%= f.text_field :link, class: 'form-control', required: true %>
          </div>
        </div>
        <div class="col-md-offset-4 col-md-2">
          <%= f.submit "Share videos", class: 'btn btn-success' %>
        </div>
      <% end %>
    </div>
  </div>
</div>